/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xo;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author l.IsSaM.l
 */
public class GAME extends javax.swing.JFrame {
    
    public static String user1; 
    public static String user2; 
    int[][] MAT = new int[4][4];
    Personne[] Menu_P = new Personne[2];
    JLabel tab_u[] = new JLabel[2];
    JLabel col[] = new JLabel[2];
    public int col_gamer ;
    JPanel  Tab_J[][] = new JPanel[4][4];
    

    /**
     * Creates new form GAME
     */
    
    
    public  void init()
           
    {
        for(int i = 0 ; i<4 ; i++)
        {
             for(int j = 0 ; j<4 ; j++)
                 MAT[i][j] = 0 ; 
        }
    }
    
    public void init_PAN()
    {
        Tab_J[0][0] =M_0_0;
        Tab_J[0][1] = M_0_1;
        Tab_J[0][2] = M_0_2;
          Tab_J[0][3] = M_0_3;
      

        Tab_J[1][0] = M_1_0;
        Tab_J[1][1] = M_1_1;
        Tab_J[1][2] = M_1_2;
         Tab_J[1][3] = M_1_3;
      

        Tab_J[2][0] = M_2_0;
        Tab_J[2][1] = M_2_1;
        Tab_J[2][2] = M_2_2;
         Tab_J[2][3] = M_2_3;
        
        Tab_J[3][0] = M_3_0;
        Tab_J[3][1] = M_3_1;
        Tab_J[3][2] = M_3_2;
         Tab_J[3][3] = M_3_3;
       
       
    }
           
    public GAME() {
        initComponents();
          this.setResizable(false);
          this.setLocationRelativeTo(null);
          TT_INIT();
           
          
    }
    
     public boolean is_Gagnant(int num_jeux)
         
     {
         int test = 0 ;
          for(int i=0 ; i<4 ; i++)
         {
             for(int j=0 ; j<4 ; j++)
             {
                 if(MAT[i][j] == num_jeux) test++ ;
             }
             if(test==4) return true;
             else 
                 test=0;
                     
         }
          
          test = 0 ;
          for(int i=0 ; i<4 ; i++)
         {
             for(int j=0 ; j<4 ; j++)
             {
                 if(MAT[j][i] == num_jeux) test++ ;
             }
             if(test==4) return true;
             else 
                 test=0;
                     
         }
           test=0;
          for(int i=0 ; i<4 ; i++)
          {
                 if(MAT[i][i] == num_jeux) test++ ;
          }
             if(test==4) return true;
             
         test = 0;      
          int i=0,j=3 ;
            while( i <4 )
          {
          if(MAT[i][j] == num_jeux) test++;
          j--;     
          i++;
          }
             if(test==4) return true;
            
    
         return false;
     }
  
    
    public boolean is_Gagnant_1(int num_jeux,int line , int colo)
    {
    boolean ttVrai = false ;    
    int k =0;
     //   System.out.println("enu_P[col_gamer].getNum_jeux()   : "+Menu_P[col_gamer].getNum_jeux());
    while ( k<3 && MAT[line][k]==Menu_P[col_gamer].getNum_jeux())
            k++;
    if(k==3) return true ;
    k=0;
    while ( k<3 && MAT[k][colo]==Menu_P[col_gamer].getNum_jeux())
            k++;
    if(k==3) return true ;
    k=0;
     k=0;
    while ( k<3 && MAT[k][k]==Menu_P[col_gamer].getNum_jeux())
            k++;
    if(k==3) return true ;

    
    return false;
    }
    public boolean  TEST_PLEINE()
    {
        boolean pleine = true ;
    
        for(int i = 0 ; i< 4 ; i++)
        {
            for(int j=0 ; j<4; j++)
                if(MAT[i][j] == 0 ) pleine=false ;
        }

        return pleine;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        u_1 = new javax.swing.JLabel();
        u_2 = new javax.swing.JLabel();
        M_0_0 = new javax.swing.JPanel();
        M_0_1 = new javax.swing.JPanel();
        M_0_2 = new javax.swing.JPanel();
        M_1_0 = new javax.swing.JPanel();
        M_1_1 = new javax.swing.JPanel();
        M_1_2 = new javax.swing.JPanel();
        M_2_0 = new javax.swing.JPanel();
        M_2_1 = new javax.swing.JPanel();
        M_2_2 = new javax.swing.JPanel();
        Retour = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        u1 = new javax.swing.JLabel();
        M_1_3 = new javax.swing.JPanel();
        M_2_3 = new javax.swing.JPanel();
        M_0_3 = new javax.swing.JPanel();
        M_3_0 = new javax.swing.JPanel();
        M_3_1 = new javax.swing.JPanel();
        M_3_3 = new javax.swing.JPanel();
        M_3_2 = new javax.swing.JPanel();
        u2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        u_1.setFont(new java.awt.Font("Sitka Text", 2, 18)); // NOI18N
        u_1.setForeground(new java.awt.Color(255, 153, 153));
        u_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        u_2.setFont(new java.awt.Font("Sitka Text", 2, 18)); // NOI18N
        u_2.setForeground(new java.awt.Color(51, 51, 255));
        u_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        M_0_0.setBackground(new java.awt.Color(255, 255, 255));
        M_0_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_0_0.setForeground(new java.awt.Color(204, 204, 255));
        M_0_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_0_0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_0_0Layout = new javax.swing.GroupLayout(M_0_0);
        M_0_0.setLayout(M_0_0Layout);
        M_0_0Layout.setHorizontalGroup(
            M_0_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        M_0_0Layout.setVerticalGroup(
            M_0_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_0_1.setBackground(new java.awt.Color(255, 255, 255));
        M_0_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_0_1.setForeground(new java.awt.Color(204, 204, 255));
        M_0_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_0_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_0_1Layout = new javax.swing.GroupLayout(M_0_1);
        M_0_1.setLayout(M_0_1Layout);
        M_0_1Layout.setHorizontalGroup(
            M_0_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        M_0_1Layout.setVerticalGroup(
            M_0_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_0_2.setBackground(new java.awt.Color(255, 255, 255));
        M_0_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_0_2.setForeground(new java.awt.Color(204, 204, 255));
        M_0_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_0_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_0_2Layout = new javax.swing.GroupLayout(M_0_2);
        M_0_2.setLayout(M_0_2Layout);
        M_0_2Layout.setHorizontalGroup(
            M_0_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_0_2Layout.setVerticalGroup(
            M_0_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_1_0.setBackground(new java.awt.Color(255, 255, 255));
        M_1_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_1_0.setForeground(new java.awt.Color(204, 204, 255));
        M_1_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_1_0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_1_0Layout = new javax.swing.GroupLayout(M_1_0);
        M_1_0.setLayout(M_1_0Layout);
        M_1_0Layout.setHorizontalGroup(
            M_1_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        M_1_0Layout.setVerticalGroup(
            M_1_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_1_1.setBackground(new java.awt.Color(255, 255, 255));
        M_1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_1_1.setForeground(new java.awt.Color(204, 204, 255));
        M_1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_1_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_1_1Layout = new javax.swing.GroupLayout(M_1_1);
        M_1_1.setLayout(M_1_1Layout);
        M_1_1Layout.setHorizontalGroup(
            M_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        M_1_1Layout.setVerticalGroup(
            M_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_1_2.setBackground(new java.awt.Color(255, 255, 255));
        M_1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_1_2.setForeground(new java.awt.Color(204, 204, 255));
        M_1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_1_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_1_2Layout = new javax.swing.GroupLayout(M_1_2);
        M_1_2.setLayout(M_1_2Layout);
        M_1_2Layout.setHorizontalGroup(
            M_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_1_2Layout.setVerticalGroup(
            M_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_2_0.setBackground(new java.awt.Color(255, 255, 255));
        M_2_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_2_0.setForeground(new java.awt.Color(204, 204, 255));
        M_2_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_2_0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_2_0Layout = new javax.swing.GroupLayout(M_2_0);
        M_2_0.setLayout(M_2_0Layout);
        M_2_0Layout.setHorizontalGroup(
            M_2_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        M_2_0Layout.setVerticalGroup(
            M_2_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_2_1.setBackground(new java.awt.Color(255, 255, 255));
        M_2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_2_1.setForeground(new java.awt.Color(204, 204, 255));
        M_2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_2_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_2_1Layout = new javax.swing.GroupLayout(M_2_1);
        M_2_1.setLayout(M_2_1Layout);
        M_2_1Layout.setHorizontalGroup(
            M_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        M_2_1Layout.setVerticalGroup(
            M_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_2_2.setBackground(new java.awt.Color(255, 255, 255));
        M_2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_2_2.setForeground(new java.awt.Color(204, 204, 255));
        M_2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_2_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_2_2Layout = new javax.swing.GroupLayout(M_2_2);
        M_2_2.setLayout(M_2_2Layout);
        M_2_2Layout.setHorizontalGroup(
            M_2_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_2_2Layout.setVerticalGroup(
            M_2_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        Retour.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Retour.setText("DECONEXION");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        u1.setOpaque(true);

        M_1_3.setBackground(new java.awt.Color(255, 255, 255));
        M_1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_1_3.setForeground(new java.awt.Color(204, 204, 255));
        M_1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_1_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_1_3Layout = new javax.swing.GroupLayout(M_1_3);
        M_1_3.setLayout(M_1_3Layout);
        M_1_3Layout.setHorizontalGroup(
            M_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_1_3Layout.setVerticalGroup(
            M_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_2_3.setBackground(new java.awt.Color(255, 255, 255));
        M_2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_2_3.setForeground(new java.awt.Color(204, 204, 255));
        M_2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_2_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_2_3Layout = new javax.swing.GroupLayout(M_2_3);
        M_2_3.setLayout(M_2_3Layout);
        M_2_3Layout.setHorizontalGroup(
            M_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_2_3Layout.setVerticalGroup(
            M_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_0_3.setBackground(new java.awt.Color(255, 255, 255));
        M_0_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_0_3.setForeground(new java.awt.Color(204, 204, 255));
        M_0_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_0_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_0_3Layout = new javax.swing.GroupLayout(M_0_3);
        M_0_3.setLayout(M_0_3Layout);
        M_0_3Layout.setHorizontalGroup(
            M_0_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_0_3Layout.setVerticalGroup(
            M_0_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_3_0.setBackground(new java.awt.Color(255, 255, 255));
        M_3_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_3_0.setForeground(new java.awt.Color(204, 204, 255));
        M_3_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_3_0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_3_0Layout = new javax.swing.GroupLayout(M_3_0);
        M_3_0.setLayout(M_3_0Layout);
        M_3_0Layout.setHorizontalGroup(
            M_3_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        M_3_0Layout.setVerticalGroup(
            M_3_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_3_1.setBackground(new java.awt.Color(255, 255, 255));
        M_3_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_3_1.setForeground(new java.awt.Color(204, 204, 255));
        M_3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_3_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_3_1Layout = new javax.swing.GroupLayout(M_3_1);
        M_3_1.setLayout(M_3_1Layout);
        M_3_1Layout.setHorizontalGroup(
            M_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        M_3_1Layout.setVerticalGroup(
            M_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        M_3_3.setBackground(new java.awt.Color(255, 255, 255));
        M_3_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_3_3.setForeground(new java.awt.Color(204, 204, 255));
        M_3_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_3_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_3_3Layout = new javax.swing.GroupLayout(M_3_3);
        M_3_3.setLayout(M_3_3Layout);
        M_3_3Layout.setHorizontalGroup(
            M_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_3_3Layout.setVerticalGroup(
            M_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        M_3_2.setBackground(new java.awt.Color(255, 255, 255));
        M_3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        M_3_2.setForeground(new java.awt.Color(204, 204, 255));
        M_3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_3_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout M_3_2Layout = new javax.swing.GroupLayout(M_3_2);
        M_3_2.setLayout(M_3_2Layout);
        M_3_2Layout.setHorizontalGroup(
            M_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        M_3_2Layout.setVerticalGroup(
            M_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        u2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(u_1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(u_2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(u2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(M_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(M_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(M_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(M_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(M_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(M_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(M_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(M_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(M_2_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(M_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(M_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(M_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(M_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(M_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Restart)
                .addGap(151, 151, 151)
                .addComponent(Retour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour)
                    .addComponent(Restart))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(u_1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(u_2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(u1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(u2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_0_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(M_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(M_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(M_0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(M_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(M_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(M_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(M_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(M_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Affichage(int[][] MAT)
    {
        for(int i = 0 ; i< 3 ; i++)
        {
             for(int j=0 ; j<3; j++)
                System.out.print(" \t"+MAT[i][j]);
              System.out.println("");
        }
        

    }
    
    public void Remplir(int i , int j  )
    {
        if(MAT[i][j]==0)
        {
            MAT[i][j]=Menu_P[col_gamer].getNum_jeux();
            Tab_J[i][j].setBackground(Menu_P[col_gamer].getCol());
         
                if(is_Gagnant(MAT[i][j]))
                { JOptionPane.showMessageDialog(null, "  Winner : "+tab_u[col_gamer].getText(), " Gratulation", JOptionPane.INFORMATION_MESSAGE); 
                  TT_INIT();
                   Restart.setVisible(true); }
                else 
                {
                    if( TEST_PLEINE() )
                    {
                  JOptionPane.showMessageDialog(null, " NO WINNER     !  ", " EQUAL RESULT", JOptionPane.INFORMATION_MESSAGE);
                
                  Restart.setVisible(true);
                  TT_INIT();
                
                   } 
               else 
            {
              tab_u[col_gamer].setVisible(false);
              col[col_gamer].setVisible(false);
              col_gamer = 1-col_gamer == 0 ? 0 : 1;
              tab_u[ col_gamer].setVisible(true);
               col[col_gamer].setVisible(true);
              
               
         
            
             }
        }
           //   Affichage(MAT);
          //    System.err.println(" \n \n ");
        }
        
       
    }
    
    
    private void M_0_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_0_0MouseClicked
     
       
        
        Remplir(0,0);  
           


// TODO add your handling code here:
    }//GEN-LAST:event_M_0_0MouseClicked

    private void M_0_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_0_1MouseClicked
Remplir(0,1);         // TODO add your handling code here:
    }//GEN-LAST:event_M_0_1MouseClicked

    private void M_0_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_0_2MouseClicked
Remplir(0,2);         // TODO add your handling code here:
    }//GEN-LAST:event_M_0_2MouseClicked

    private void M_1_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_1_0MouseClicked
Remplir(1,0);         // TODO add your handling code here:
    }//GEN-LAST:event_M_1_0MouseClicked

    private void M_1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_1_1MouseClicked
Remplir(1,1);         // TODO add your handling code here:
    }//GEN-LAST:event_M_1_1MouseClicked

    private void M_1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_1_2MouseClicked
Remplir(1,2);         // TODO add your handling code here:
    }//GEN-LAST:event_M_1_2MouseClicked

    private void M_2_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_2_0MouseClicked
Remplir(2,0);         // TODO add your handling code here:
    }//GEN-LAST:event_M_2_0MouseClicked

    private void M_2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_2_1MouseClicked
Remplir(2,1);         // TODO add your handling code here:
    }//GEN-LAST:event_M_2_1MouseClicked

    private void M_2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_2_2MouseClicked
Remplir(2,2);         // TODO add your handling code here:
    }//GEN-LAST:event_M_2_2MouseClicked

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
this.dispose();
new MENU().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_RetourActionPerformed

    
    
    public void TT_INIT()
    {
        
        Restart.setVisible(true);
        boolean enTOur = Math.random() < 0.40 ? true : false ;
          if(enTOur)
              col_gamer = 0;
          else 
              col_gamer = 1 ;
          init_PAN();
          Menu_P[0] = new Personne(Color.red,1,enTOur , user1 ) ;
          Menu_P[1] = new Personne(Color.BLUE,2,!enTOur , user2 ) ;
          init();
          tab_u[0] = u_1 ;
          tab_u[1] = u_2 ;
           tab_u[0].setForeground(Menu_P[0].getCol());
          tab_u[1].setForeground(Menu_P[1].getCol());
          u1.setBackground(Menu_P[0].getCol());
          u2.setBackground(Menu_P[1].getCol());
          tab_u[0].setText(Menu_P[0].getNom());
           tab_u[0].setVisible(Menu_P[0].isSonTour());
            u1.setVisible(Menu_P[0].isSonTour());
         
          tab_u[1].setText(Menu_P[1].getNom());
           tab_u[1].setVisible(Menu_P[1].isSonTour());
            u2.setVisible(Menu_P[1].isSonTour());
            col[0] = u1 ;
            col[1] = u2 ;
           for ( int i = 0 ; i<4 ; i++)
        {
            for( int j = 0 ; j<4 ; j++)
            Tab_J[i][j].setBackground(Color.white);
        }
           
    }
    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
TT_INIT();         // TODO add your handling code here:
    }//GEN-LAST:event_RestartActionPerformed

    private void M_1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_1_3MouseClicked
Remplir(1,3);           // TODO add your handling code here:
    }//GEN-LAST:event_M_1_3MouseClicked

    private void M_2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_2_3MouseClicked
Remplir(2,3);           // TODO add your handling code here:
    }//GEN-LAST:event_M_2_3MouseClicked

    private void M_0_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_0_3MouseClicked
        Remplir(0,3);        // TODO add your handling code here:
    }//GEN-LAST:event_M_0_3MouseClicked

    private void M_3_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_3_0MouseClicked
Remplir(3,0);           // TODO add your handling code here:
    }//GEN-LAST:event_M_3_0MouseClicked

    private void M_3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_3_1MouseClicked
Remplir(3,1);           // TODO add your handling code here:
    }//GEN-LAST:event_M_3_1MouseClicked

    private void M_3_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_3_3MouseClicked
Remplir(3,3);           // TODO add your handling code here:
    }//GEN-LAST:event_M_3_3MouseClicked

    private void M_3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_3_2MouseClicked
Remplir(3,2);           // TODO add your handling code here:
    }//GEN-LAST:event_M_3_2MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
 
    /**
     * @param args the command line arguments
     */
    
    public int get_col_of_gamer()
    {
        for(int i =0 ; i<2 ; i++)
        { if(Menu_P[i].isSonTour())
            return i ;
        
         }
        return -1;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel M_0_0;
    private javax.swing.JPanel M_0_1;
    private javax.swing.JPanel M_0_2;
    private javax.swing.JPanel M_0_3;
    private javax.swing.JPanel M_1_0;
    private javax.swing.JPanel M_1_1;
    private javax.swing.JPanel M_1_2;
    private javax.swing.JPanel M_1_3;
    private javax.swing.JPanel M_2_0;
    private javax.swing.JPanel M_2_1;
    private javax.swing.JPanel M_2_2;
    private javax.swing.JPanel M_2_3;
    private javax.swing.JPanel M_3_0;
    private javax.swing.JPanel M_3_1;
    private javax.swing.JPanel M_3_2;
    private javax.swing.JPanel M_3_3;
    private javax.swing.JButton Restart;
    private javax.swing.JButton Retour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel u1;
    private javax.swing.JLabel u2;
    private javax.swing.JLabel u_1;
    private javax.swing.JLabel u_2;
    // End of variables declaration//GEN-END:variables
}
